// <auto-generated />
namespace StokTakipSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class FixRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202511141936169_FixRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
